version: '3.8'

services:
  web:
    build: .
    command: gunicorn --bind 0.0.0.0:8000 stocksentiment.wsgi:application
    ports:
      - "8000:8000"
    environment:
      - PGDATABASE=neondb
      - PGUSER=neondb_owner
      - PGPASSWORD=npg_4ZUCGV8cWRIl
      - PGHOST=ep-empty-truth-a72h94an-pooler.ap-southeast-2.aws.neon.tech
      - PGPORT=5432
      - SSLMODE=require
      - CELERY_BROKER_URL=redis://default:OKmsmzf8rASGhRsmMdx3OJX3SVPWydMo@redis-11805.crce182.ap-south-1-1.ec2.redns.redis-cloud.com:11805/0
      - CELERY_RESULT_BACKEND=redis://default:OKmsmzf8rASGhRsmMdx3OJX3SVPWydMo@redis-11805.crce182.ap-south-1-1.ec2.redns.redis-cloud.com:11805/0

# You don't need volumes or extra services


# volumes:
#   # In your case, you don't need any volumes since they are hosted elsewhere (Redis and PostgreSQL)
#   # You can remove this section completely if it's not required, or keep it empty
